### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bmaciag**
folder name need to be "sapdownloads"

### CODE REVIEW

**Review by brandoncaulfield — APPROVED** [review]
Thanks @bmaciag for finding that. Weird thing is when I filmed the video it still worked! Not sure why but perhaps I missed something.

**Comment by bmaciag** [comment]
Hi @brandoncaulfield ,

could you maybe add the label "hacktoberfest-accepted" to this PR?

Best, B.

**Comment by bmaciag** [comment]
Please :)

**Comment by brandoncaulfield** [comment]
No worries :)

**Pull request merged**
